language: python
python:
    - "3.5"
    - "3.6"
    - "3.7-dev"
cache: pip
install:
  - pip install -r fullcyclepy/requirements.txt
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/fullcyclepy/
  - python fullcyclepy/tests/test_mining.py
