language: python
python:
    - "3.5"
    - "3.6"
    - "3.7-dev"
cache: pip
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
install:
  - pip install -r fullcyclepy/requirements.txt
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/fullcyclepy/
  - pytest
  - py.test --cov --cov-config .coveragerc
after_success:
    - coveralls
