language: python
python:
    - "3.5"
    - "3.6"
    - "3.7-dev"
cache: pip
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
#    - pip install python-coveralls
#    - pip install nose
install:
  - pip install -r fullcyclepy/requirements.txt
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/fullcyclepy/
  - pytest
  - pytest --cov
#  - nosetests --with-coverage --cover-tests
#  - cd fullcyclepy/tests
#  - coverage erase
#  - coverage run -a test_mining.py
#  - coverage run -a test_rules.py
#  - coverage run -a test_bus.py
#  - coverage run -a test_json_message.py
#  - coverage run -a test_minerapi.py
#  - coverage run -a test_pools.py
#  - coverage run -a test_queuenames.py
#  - coverage run -a test_taskscheduler.py
after_success:
    - coveralls
